### ISSUE TITLE
Include fswatch

### ISSUE THREAD

**Issue by fabienheureux** [nobe4/yada#1]
What do you think of adding fswatch (https://github.com/emcrisostomo/fswatch) in order to: 
- Monitor for changes in files, & automatically run the yada script

**Comment by nobe4** [comment]
It could make sense but `yada` was created with the following workflow in mind:

1. Create your files
2. Run `install`
3. Edit the files
4. Repeat **3** / Start again from **1**

What that means it that you don't need to run anything if you are not creating any new file. And it's supposedly not something you do every day.

 So adding any kind of file-creation tracking would be _de trop_.
